### ISSUE TITLE
[Bug] Error: Cannot find module '../build_info'

### ISSUE THREAD

**Issue by FichteFoll** [rauenzi/BetterDiscordApp#234]
**Describe the Bug**
After installing BBD with bdctl discord, fails to start. Only on my laptop, however.

**To Reproduce**
1. `betterdiscordctl uninstall`
1. `rm -rf /home/fichte/.config/discord/0.0.9`
1. start discord once to have it fetch its modules
1. 
  ```
~ $ betterdiscordctl install -b /usr/lib/betterdiscord-rauenzi-git -v -v
VV: Scanning /opt
VV: Trying flavor ''
V: Using Discord at /opt/discord
V: Found modules in /home/fichte/.config/discord/0.0.9/modules
V: Injecting into index.js...
V: Linking BetterDiscord injector...
Installed. (Restart Discord if necessary.)
  ```
5) restart discord

**Screenshots**
![2019-08-20_15-48-12](https://user-images.githubusercontent.com/931051/63353101-852c6000-c362-11e9-9461-0abc83c3e422.png)

**Discord Version**
```
~ ¬ pacman -Qs discord
local/betterdiscord-rauenzi-git 0.3.2.r13.g2123673-1
    Discord extension with plugin support, emotes, and more (rauenzi's updated fork)
local/betterdiscordctl-git 1.6.1.r35.g5f13ec2-1
    A utility for managing BetterDiscord on Linux
local/discord 0.0.9-4
    All-in-one voice and text chat for gamers that's free and secure.
```

**Comment by FichteFoll** [comment]
Well, that's embarassing. I was confident I was running the latest version because I checked this like 2 weeks ago where it didn't work, but looks like it has been fixed since. Works with `0.3.2.r14.g1434e53-1`.
